version: '3'
services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      # This port is for Webhooks
      - "9001:9001"
    volumes:
      - /PATH_TO_YOUR_CONFIG:/mosquitto/config
      - /PATH_TO_YOUR_DATA:/mosquitto/data
      - /PATH_TO_YOUR_LOG:/mosquitto/log
      
